version: "3.9"
services:
  api:
    build: ./NedVision.Api
    ports:
      - "8080:8080"
    depends_on:
      - analytics

  analytics:
    build: ./analytics
    ports:
      - "8000:8000"

  web:
    build: ./nedvision-web
    ports:
      - "4200:80"
